/* LES DEUX ARTICLES DU CODE PÉNAL QUE L'AFFICHAGE DOIT PORTER.

   L. 1152-4 et L. 1153-5 obligent à porter à la connaissance des salariés le
   TEXTE de ces deux articles, non leur numéro ni un résumé. Le relais
   Légifrance du dépôt ne sert que le code du travail : ils ont donc été lus
   ailleurs, et l'écran de contrôle des affichages les reproduisait déjà,
   mot pour mot, avec leur identifiant de version.

   Le parcours, lui, laissait un crochet : « [TEXTE À REPORTER, l'article
   222-33 du code pénal, en entier…] ». Deux générateurs pour le même texte,
   l'un qui l'a et l'autre qui l'ignore. Relevé le 29 septembre 2026. Ce
   fichier est la source unique : l'écran de contrôle et les documents du
   parcours y puisent tous les deux.

   Lecture : trois lectures espacées par article, identifiant de version
   stable aux trois lectures, le 7 septembre 2026. C'est le contenu qui
   tranche, et chacun de ces textes parle bien de ce pour quoi il est cité. */
(function (global) {
  "use strict";

  var LU = "lu le 7 septembre 2026";

  var CP = {
    "222-33": { id: "LEGIARTI000054724663", nom: "Article 222-33 du code pénal",
      t: "I. - Le harcèlement sexuel est le fait d'imposer à une personne, de façon répétée, des propos ou comportements à connotation sexuelle ou sexiste qui soit portent atteinte à sa dignité en raison de leur caractère dégradant ou humiliant, soit créent à son encontre une situation intimidante, hostile ou offensante. L'infraction est également constituée : 1° Lorsque ces propos ou comportements sont imposés à une même victime par plusieurs personnes, de manière concertée ou à l'instigation de l'une d'elles, alors même que chacune de ces personnes n'a pas agi de façon répétée ; 2° Lorsque ces propos ou comportements sont imposés à une même victime, successivement, par plusieurs personnes qui, même en l'absence de concertation, savent que ces propos ou comportements caractérisent une répétition. II. - Est assimilé au harcèlement sexuel le fait, même non répété, d'user de toute forme de pression grave dans le but réel ou apparent d'obtenir un acte de nature sexuelle, que celui-ci soit recherché au profit de l'auteur des faits ou au profit d'un tiers. III. - Les faits mentionnés aux I et II sont punis de deux ans d'emprisonnement et de 30 000 € d'amende. Ces peines sont portées à trois ans d'emprisonnement et 45 000 € d'amende lorsque les faits sont commis : 1° Par une personne qui abuse de l'autorité que lui confèrent ses fonctions ; 2° Sur un mineur de quinze ans ; 3° Sur une personne dont la particulière vulnérabilité, due à son âge, à une maladie, à une infirmité, à une déficience physique ou psychique ou à un état de grossesse, est apparente ou connue de leur auteur ; 4° Sur une personne dont la particulière vulnérabilité ou dépendance résultant de la précarité de sa situation économique ou sociale est apparente ou connue de leur auteur ; 5° Par plusieurs personnes agissant en qualité d'auteur ou de complice ; 6° Par l'utilisation d'un service de communication au public en ligne ou par le biais d'un support numérique ou électronique ; 7° Alors qu'un mineur était présent et y a assisté ; 8° Par un ascendant ou par toute autre personne ayant sur la victime une autorité de droit ou de fait ; 9° Dans un moyen de transport collectif de voyageurs ou dans un lieu destiné à l'accès à un moyen de transport collectif de voyageurs." },
    "222-33-2": { id: "LEGIARTI000029336939", nom: "Article 222-33-2 du code pénal",
      t: "Le fait de harceler autrui par des propos ou comportements répétés ayant pour objet ou pour effet une dégradation des conditions de travail susceptible de porter atteinte à ses droits et à sa dignité, d'altérer sa santé physique ou mentale ou de compromettre son avenir professionnel, est puni de deux ans d'emprisonnement et de 30 000 € d'amende." },
    "225-1": { id: "LEGIARTI000045391831", nom: "Article 225-1 du code pénal",
      t: "Constitue une discrimination toute distinction opérée entre les personnes physiques sur le fondement de leur origine, de leur sexe, de leur situation de famille, de leur grossesse, de leur apparence physique, de la particulière vulnérabilité résultant de leur situation économique, apparente ou connue de son auteur, de leur patronyme, de leur lieu de résidence, de leur état de santé, de leur perte d'autonomie, de leur handicap, de leurs caractéristiques génétiques, de leurs mœurs, de leur orientation sexuelle, de leur identité de genre, de leur âge, de leurs opinions politiques, de leurs activités syndicales, de leur qualité de lanceur d'alerte, de facilitateur ou de personne en lien avec un lanceur d'alerte au sens, respectivement, du I de l'article 6 et des 1° et 2° de l'article 6-1 de la loi n° 2016-1691 du 9 décembre 2016 relative à la transparence, à la lutte contre la corruption et à la modernisation de la vie économique, de leur capacité à s'exprimer dans une langue autre que le français, de leur appartenance ou de leur non-appartenance, vraie ou supposée, à une ethnie, une Nation, une prétendue race ou une religion déterminée. Constitue également une discrimination toute distinction opérée entre les personnes morales sur le fondement de l'origine, du sexe, de la situation de famille, de la grossesse, de l'apparence physique, de la particulière vulnérabilité résultant de la situation économique, apparente ou connue de son auteur, du patronyme, du lieu de résidence, de l'état de santé, de la perte d'autonomie, du handicap, des caractéristiques génétiques, des mœurs, de l'orientation sexuelle, de l'identité de genre, de l'âge, des opinions politiques, des activités syndicales, de la qualité de lanceur d'alerte, de facilitateur ou de personne en lien avec un lanceur d'alerte, au sens, respectivement, du I de l'article 6 et des 1° et 2° de l'article 6-1 de la loi n° 2016-1691 du 9 décembre 2016 précitée, de la capacité à s'exprimer dans une langue autre que le français, de l'appartenance ou de la non-appartenance, vraie ou supposée, à une ethnie, une Nation, une prétendue race ou une religion déterminée des membres ou de certains membres de ces personnes morales." },
    "225-2": { id: "LEGIARTI000033975382", nom: "Article 225-2 du code pénal",
      t: "La discrimination définie aux articles 225-1 à 225-1-2, commise à l'égard d'une personne physique ou morale, est punie de trois ans d'emprisonnement et de 45 000 euros d'amende lorsqu'elle consiste : 1° A refuser la fourniture d'un bien ou d'un service ; 2° A entraver l'exercice normal d'une activité économique quelconque ; 3° A refuser d'embaucher, à sanctionner ou à licencier une personne ; 4° A subordonner la fourniture d'un bien ou d'un service à une condition fondée sur l'un des éléments visés à l'article 225-1 ou prévue aux articles 225-1-1 ou 225-1-2 ; 5° A subordonner une offre d'emploi, une demande de stage ou une période de formation en entreprise à une condition fondée sur l'un des éléments visés à l'article 225-1 ou prévue aux articles 225-1-1 ou 225-1-2 ; 6° A refuser d'accepter une personne à l'un des stages visés par le 2° de l'article L. 412-8 du code de la sécurité sociale. Lorsque le refus discriminatoire prévu au 1° est commis dans un lieu accueillant du public ou aux fins d'en interdire l'accès, les peines sont portées à cinq ans d'emprisonnement et à 75 000 euros d'amende." },
    "225-3": { id: "LEGIARTI000043895868", nom: "Article 225-3 du code pénal",
      t: "Les dispositions de l'article précédent ne sont pas applicables : 1° Aux discriminations fondées sur l'état de santé, lorsqu'elles consistent en des opérations ayant pour objet la prévention et la couverture du risque décès, des risques portant atteinte à l'intégrité physique de la personne ou des risques d'incapacité de travail ou d'invalidité. Toutefois, ces discriminations sont punies des peines prévues à l'article précédent lorsqu'elles se fondent sur la prise en compte de tests génétiques prédictifs ayant pour objet une maladie qui n'est pas encore déclarée ou une prédisposition génétique à une maladie ou qu'elles se fondent sur la prise en compte des conséquences sur l'état de santé d'un prélèvement d'organe tel que défini à l'article L. 1231-1 du code de la santé publique ou de données issues de techniques d'imagerie cérébrale ; 2° Aux discriminations fondées sur l'état de santé ou le handicap, lorsqu'elles consistent en un refus d'embauche ou un licenciement fondé sur l'inaptitude médicalement constatée soit dans le cadre du titre IV du livre II du code du travail, soit dans le cadre des lois portant dispositions statutaires relatives à la fonction publique ; 3° Aux discriminations fondées, en matière d'embauche, sur un motif mentionné à l'article 225-1 du présent code, lorsqu'un tel motif constitue une exigence professionnelle essentielle et déterminante et pour autant que l'objectif soit légitime et l'exigence proportionnée ; 4° Aux discriminations fondées, en matière d'accès aux biens et services, sur le sexe lorsque cette discrimination est justifiée par la protection des victimes de violences à caractère sexuel, des considérations liées au respect de la vie privée et de la décence, la promotion de l'égalité des sexes ou des intérêts des hommes ou des femmes, la liberté d'association ou l'organisation d'activités sportives ; 5° Aux refus d'embauche fondés sur la nationalité lorsqu'ils résultent de l'application des dispositions statutaires relatives à la fonction publique ; 6° Aux discriminations liées au lieu de résidence lorsque la personne chargée de la fourniture d'un bien ou service se trouve en situation de danger manifeste. Les mesures prises en faveur des personnes résidant dans certaines zones géographiques et visant à favoriser l'égalité de traitement ne constituent pas une discrimination." },
    "225-4": { id: "LEGIARTI000020630926", nom: "Article 225-4 du code pénal",
      t: "Les personnes morales déclarées responsables pénalement, dans les conditions prévues par l'article 121-2, des infractions définies à l'article 225-2 encourent, outre l'amende suivant les modalités prévues par l'article 131-38, les peines prévues par les 2° à 5°, 8° et 9° de l'article 131-39. L'interdiction mentionnée au 2° de l'article 131-39 porte sur l'activité dans l'exercice ou à l'occasion de l'exercice de laquelle l'infraction a été commise." },
  };

  global.TextesPenal = { CP: CP, LU: LU,
    /* Le texte d'un article, prêt à être recopié sur l'affiche, avec la
       mention de sa version : c'est elle qui protège l'employeur. */
    bloc: function (num) {
      var a = CP[num];
      if (!a) return null;
      return { nom: a.nom, id: a.id, t: a.t, lu: LU };
    } };
})(typeof window !== "undefined" ? window : this);
